version: "3"
services:

  portainer:
    image: portainer/portainer-ee:latest
    ports:
      - 9443:9443
      - 8000:8000
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/opt:/var/opt
    restart: unless-stopped

volumes:
  portainer-data: