version: "3.9"

networks:
  frontend:
    external: true
  backend:
    external: true

services:
  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/opt/traefik:/var/opt/traefik
      - /var/opt/traefik/config:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      # - CF_DNS_API_TOKEN=insert-cloudflare-api-token
    networks:
      - frontend
      - backend
    restart: unless-stopped
